### ISSUE TITLE
개발 문서 pdf 파일 5페이지 관련 질문 드립니다.

### ISSUE THREAD

**Issue by feel-coding** [dbasen-tbase/searchanalyzer#3]
회원가입 화면에
![회원가입 예시화면](https://user-images.githubusercontent.com/46566478/115361376-7c58f500-a1fb-11eb-9632-4a4cc1bfc1aa.PNG)
위와 같이 이름을 입력하는 란에 "숫자/영어/특수문자 8자 이상"이라고 되어있는데 ID, PW 말고 이름도 유효성 검사를 해야하는지 궁금합니다. 답변 주시면 정말 감사하겠습니다.

**Comment by dbase-n** [comment]
@feel-coding
이름의 placeholder 값이 잘못 입력되었습니다.
무시하시고 진행하시면 됩니다.

**Comment by feel-coding** [comment]
@dbase-n 감사합니다.
