### ISSUE TITLE
[문의] 화면 설계서 pdf 중 실시간 검색 결과 질문드립니다.

### ISSUE THREAD

**Issue by Jiyoung-h** [dbasen-tbase/searchanalyzer#4]
p.7 에 예시에 나온 표에서
No.|URL|타이틀|검색어 출연수
--|--|--|--
1|http://www.dbase.co.kr|디베이스앤|2

본문에 **검색어 출현수**가 ***2***로 표기되어 있으나
p.4 에 '디베이스앤' 검색 결과에서 본문을 보면 
> 검색, 퍼포먼스, 디스플레이 광고 대행 및 통합 컨설팅 지원, DBASE&.

검색어 '디베이스앤'에 해당하는 문자열이 없습니다.
제가 이해한 바가 틀린 건지, 정확한 데이터가 아닌 예시를 든 것인지 궁금합니다.

**Comment by dbase-n** [comment]
@Jiyoung-h 

해당 부분은 샘플 화면을 구성하기 위해서 "2"로 표시한 부분입니다.
결론적으로 예시화면이니 무시하시고 진행하시면 됩니다.

실제 구현시에는 검색 본문에 검색어가 몇번 나타나는지를 카운트한 값입니다.

**Comment by Jiyoung-h** [comment]
@dbase-n 네 감사합니다.
