### ISSUE TITLE
[문의] 과제 5페이지의 유저 아이디 길이

### ISSUE THREAD

**Issue by penguin418** [dbasen-tbase/searchanalyzer#5]
화면 설계서 5페이지에는 글 부분 설명으론, 유저 아이디가 10자 이상이지만, 그림 설명에선 유저 아이디가 20자 이상으로 충돌되는 것을 발견했습니다. 어떤 명세를 따라야 할지 알려주시면 좋겠습니다.

감사합니다.

**Comment by dbase-n** [comment]
@penguin418 
설명 그림은 무시하시고, 글 설명을 기준으로 진행하시면 됩니다.
화면설계상에 오류입니다.

**Comment by penguin418** [comment]
감사합니다.
