### ISSUE TITLE
[문의] admin 계정

### ISSUE THREAD

**Issue by GreatLaboratory** [dbasen-tbase/searchanalyzer#6]
pdf 6페이지 화면설계서에서
기본 셋팅인 admin/1234 계정으로 로그인하려고 시도할 때 
`비밀번호는 8이상, 2개 이상 중복된 문자 불가, 특수문자/숫자/영어로 구성` 유효성검사로 인해 로그인이 불가능해지는데(로그인하려는 비밀번호가 1234여서)

기본 셋팅을 admin/qwer1234! 으로 변경해도 괜찮나요? @dbase-n

**Comment by dbase-n** [comment]
@GreatLaboratory 
네 가능합니다. 프로젝트 시작할때 강제 설정만 되면 됩니다.

**Comment by GreatLaboratory** [comment]
@dbase-n 
네 감사합니다.
