### ISSUE TITLE
[문의] 연관검색어 선정 기준

### ISSUE THREAD

**Issue by Beakjiyeon** [dbasen-tbase/searchanalyzer#7]
(자료 9페이지)

연관검색어 선정기준 표현에 대해 문의가 있습니다. 

' **단어출현수 / keyword검색수** '는 keyword을 한 번 검색할때 나오는 결과에 대해서

본문 중 비율이 0.5 이상인 단어를 찾는게 아니고,

단어가 검색 되냐 안되냐 여부를 따져서 

_예를 들어 dbasen를 2번 검색했을 때 
특정 단어가 첫번째 검색에서는 나오고, 두번째 검색할 때는 나오지 않는다면 
즉, 1번만 나온다면 출현수(1)/검색수(2) >= 0.5 니까 연관 검색어로 본다_. 

이런식으로 문제를 이해하고 진행해도 될까요?

**Comment by dbase-n** [comment]
@Beakjiyeon 
네 정확하게 이해하셨습니다.
